server:  
  port: 8084
  context-path: /mtg-card-catalogue

mtg:
  imageHost: http://localhost:8080/mtg-image-server
  initializeCardsRepositoryOnStartup: false
  cardInitializer:
    sourceUrl: https://api.deckbrew.com/mtg/cards
    absoluteProjectPath: C:/Users/jbo/IdeaProjects/spring-boot-tutorial
    projectImageDir: /src/main/resources/static
    webappImageDir: /img/cards

eureka:  
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true